language: python
python:
    - "3.6"
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install: "sudo pip install -r requirements.txt"
script:
    - SECRET_KEY="whatever" python manage.py test